#!/usr/bin/env bash

DIR="$HOME/.config/rofi/"

rofi \
	-theme "$DIR"/telescope.rasi \
	-show
	# -no-lazy-grab \
	# -scroll-method 0 \
	# -drun-match-fields all \
	# -drun-display-format "{name}" \
	# -no-drun-show-actions \
	# -terminal wezterm
