#!/usr/bin/env bash

# get saku
echo "> INSTALLING SAKU <"
curl -fsSL https://raw.githubusercontent.com/CrispyBaccoon/saku/mega/install.sh | sh
eval "$(~/.saku/root/bin/sk env)"

echo "> INSTALLING sk PACKAGES < "
sk install rust
sk install neovim
sk install tmux
sk install lime

# get dotfiles
echo "> CLONING DOTFILES <"
cd
git clone --filter=blob:none https://github.com/comfysage/dotfiles.git ~/.dots
cd ~/.dots
git submodule update --init --recursive

echo "> LINKING DOTFILES <"
./install.sh
